/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "surface": "#111316",
                "surface-dim": "#111316",
                "surface-bright": "#37393d",
                "surface-container-lowest": "#0c0e11",
                "surface-container-low": "#1a1c1f",
                "surface-container": "#1e2023",
                "surface-container-high": "#282a2d",
                "surface-container-highest": "#333538",
                "on-surface": "#e2e2e6",
                "on-surface-variant": "#bdc9c6",
                "inverse-surface": "#e2e2e6",
                "inverse-on-surface": "#2f3034",
                "outline": "#889391",
                "outline-variant": "#3e4947",
                "surface-tint": "#7ed6cb",
                "primary": "#7ed6cb",
                "on-primary": "#003733",
                "primary-container": "#459f95",
                "on-primary-container": "#00302c",
                "inverse-primary": "#006a62",
                "secondary": "#c1c7d0",
                "on-secondary": "#2b3138",
                "secondary-container": "#41474f",
                "on-secondary-container": "#b0b5be",
                "tertiary": "#ffb59b",
                "on-tertiary": "#562009",
                "tertiary-container": "#cc7c5f",
                "on-tertiary-container": "#4d1904",
                "error": "#ffb4ab",
                "on-error": "#690005",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                "primary-fixed": "#9bf2e7",
                "primary-fixed-dim": "#7ed6cb",
                "on-primary-fixed": "#00201d",
                "on-primary-fixed-variant": "#00504a",
                "secondary-fixed": "#dde3ec",
                "secondary-fixed-dim": "#c1c7d0",
                "on-secondary-fixed": "#161c23",
                "on-secondary-fixed-variant": "#41474f",
                "tertiary-fixed": "#ffdbcf",
                "tertiary-fixed-dim": "#ffb59b",
                "on-tertiary-fixed": "#380d00",
                "on-tertiary-fixed-variant": "#72351d",
                "background": "#111316",
                "on-background": "#e2e2e6",
                "surface-variant": "#333538",
                "surface-base": "#121417",
                "surface-card": "#181B20",
                "surface-elevated": "#1F242B",
                "border-subtle": "#2D333B",
                "border-strong": "#30363D",
                "text-primary": "#E6EDF3",
                "text-secondary": "#C9D1D9",
                "text-muted": "#8B949E",
                "status-pending": "#D97706",
                "status-pending-bg": "#2A1E0D",
                "status-accepted": "#10B981",
                "status-accepted-bg": "#0D2A20",
                "status-rejected": "#E11D48",
                "status-rejected-bg": "#2F1119",
                "status-completed": "#3B82F6",
                "status-completed-bg": "#12213D",
                "badge-wanted-border": "#4B5563",
                "badge-wanted-bg": "#1E232B"
            },
            fontFamily: {
                "sans": ["Manrope", "sans-serif"],
                "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
            },
            fontSize: {
                "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "600" }],
                "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
                "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
                "caption": ["11px", { lineHeight: "14px", fontWeight: "400" }]
            },
            borderRadius: {
                "sm": "0.125rem",
                "DEFAULT": "0.25rem",
                "md": "0.375rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "gutter": "1.25rem",
                "gutter-mobile": "0.75rem",
                "margin": "2rem",
                "margin-mobile": "1rem",
                "space-xs": "0.25rem",
                "space-sm": "0.5rem",
                "space-md": "1rem",
                "space-lg": "1.5rem",
                "space-xl": "2rem"
            }
        }
    },
    plugins: [],
}
