/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: "class",
      darkMode: "class",
    theme: {
      extend: {
        "colors": {
          "error": "#ba1a1a",
          "surface-dim": "#cbdbf5",
          "surface-tint": "#2151da",
          "on-primary": "#ffffff",
          "secondary": "#565e74",
          "on-secondary": "#ffffff",
          "on-primary-container": "#cad3ff",
          "on-tertiary-container": "#76eab6",
          "surface-container-high": "#dce9ff",
          "on-surface": "#0b1c30",
          "on-tertiary-fixed-variant": "#005137",
          "secondary-container": "#dae2fd",
          "surface": "#f8f9ff",
          "surface-container": "#e5eeff",
          "tertiary": "#004f35",
          "surface-bright": "#f8f9ff",
          "on-error-container": "#93000a",
          "outline": "#747686",
          "on-secondary-fixed": "#131b2e",
          "inverse-primary": "#b7c4ff",
          "primary-fixed": "#dce1ff",
          "primary": "#0037b0",
          "inverse-surface": "#213145",
          "tertiary-fixed-dim": "#68dba9",
          "on-background": "#0b1c30",
          "on-surface-variant": "#434655",
          "on-primary-fixed": "#001551",
          "surface-container-low": "#eff4ff",
          "on-secondary-container": "#5c647a",
          "outline-variant": "#c4c5d7",
          "on-secondary-fixed-variant": "#3f465c",
          "tertiary-fixed": "#85f8c4",
          "on-primary-fixed-variant": "#0039b5",
          "tertiary-container": "#006948",
          "primary-container": "#1d4ed8",
          "inverse-on-surface": "#eaf1ff",
          "surface-container-highest": "#d3e4fe",
          "surface-variant": "#d3e4fe",
          "on-tertiary": "#ffffff",
          "surface-container-lowest": "#ffffff",
          "background": "#f8f9ff",
          "on-error": "#ffffff",
          "secondary-fixed-dim": "#bec6e0",
          "primary-fixed-dim": "#b7c4ff",
          "on-tertiary-fixed": "#002114",
          "error-container": "#ffdad6",
          "secondary-fixed": "#dae2fd"
        },
        "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
        },
        "spacing": {
          "gutter-mobile": "1rem",
          "margin": "2rem",
          "space-md": "1rem",
          "space-sm": "0.5rem",
          "space-xs": "0.25rem",
          "gutter": "1.5rem",
          "space-lg": "1.5rem",
          "space-xl": "2rem",
          "margin-mobile": "1rem"
        },
        "fontFamily": {
          "body-sm": ["Inter"],
          "label-sm": ["Inter"],
          "headline-xl": ["Inter"],
          "title-lg": ["Inter"],
          "headline-sm": ["Inter"],
          "label-md": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "headline-lg": ["Inter"],
          "headline-xl-mobile": ["Inter"],
          "title-md": ["Inter"],
          "body-md": ["Inter"],
          "headline-md": ["Inter"],
          "body-lg": ["Inter"]
        },
        "fontSize": {
          "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.005em", "fontWeight": "400" }],
          "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600" }],
          "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "700" }],
          "title-lg": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
          "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
          "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
          "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
          "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }]
        }
      }
    }
 
};
