# Generated by Django 6.0.7 on 2026-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
